In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pandas import read_csv

In [4]:
data=pd.read_csv('/content/drive/MyDrive/S2 (1)/epl-goalScorer(20-21).csv')
data.head(15)

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,18,3,0,F S,Everton,16,18.136449,19.698850,4.159406
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,28,1,0,F S,Leicester,7,13.092427,18.227907,2.412588
7,7,8865,Ollie Watkins,37,3330,14,16.280178,5,5.314029,98,45,2,1,F,Aston Villa,13,14.757840,22.014021,5.334991
8,8,314,Ilkay GÃ¼ndogan,28,2033,13,9.566883,2,3.816220,54,42,1,0,M S,Manchester City,12,8.044545,19.286812,10.148375
9,9,3277,Alexandre Lacazette,30,1928,13,12.028909,2,2.209213,45,22,3,0,F M S,Arsenal,10,9.745403,14.361542,2.937941
10,10,468,Callum Wilson,26,2079,12,13.590091,5,3.046301,49,17,2,0,F S,Newcastle United,8,10.545416,14.205593,1.052545
11,11,620,Kelechi Iheanacho,25,1452,12,9.048596,2,3.534099,59,28,1,0,F S,Leicester,12,8.287427,13.961564,3.429915
12,12,986,Danny Ings,28,2115,12,8.139229,4,2.311231,56,22,1,0,F S,Southampton,10,6.616892,9.929089,2.063256
13,13,4456,Chris Wood,32,2675,12,12.896009,3,2.038118,69,23,0,0,F S,Burnley,10,11.373671,13.585282,2.149852
14,14,522,Wilfried Zaha,30,2615,11,8.804440,2,3.702821,60,30,6,0,F M S,Crystal Palace,9,7.282102,13.579472,3.634436

**10 player terbanyak mencetak goal**

In [5]:
goal = data['goals'].value_counts()
goal

0     255
1     108
2      49
3      29
4      14
8      10
5       9
6       9
7       7
10      7
9       6
11      5
12      4
13      2
17      2
22      1
14      1
15      1
16      1
18      1
23      1
Name: goals, dtype: int64

In [6]:
goal = data.nlargest(10,'goals')
goal

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,18,3,0,F S,Everton,16,18.136449,19.698850,4.159406
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,28,1,0,F S,Leicester,7,13.092427,18.227907,2.412588
7,7,8865,Ollie Watkins,37,3330,14,16.280178,5,5.314029,98,45,2,1,F,Aston Villa,13,14.757840,22.014021,5.334991
8,8,314,Ilkay GÃ¼ndogan,28,2033,13,9.566883,2,3.816220,54,42,1,0,M S,Manchester City,12,8.044545,19.286812,10.148375
9,9,3277,Alexandre Lacazette,30,1928,13,12.028909,2,2.209213,45,22,3,0,F M S,Arsenal,10,9.745403,14.361542,2.937941

**10 Player terlama durasi main**

In [7]:
durasi = data['time'].value_counts()
durasi

90      10
1        7
3330     7
270      4
180      4
        ..
1865     1
2447     1
1252     1
1109     1
67       1
Name: time, Length: 441, dtype: int64

In [8]:
durasi = data.nlargest(10,'time')
durasi

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
110,110,343,Pierre-Emile HÃ¸jbjerg,38,3420,2,1.137927,4,1.755895,14,16,9,0,M,Tottenham,2,1.137927,16.205809,14.680379
296,296,637,Hugo Lloris,38,3420,0,0.000000,0,0.000000,0,0,0,0,GK,Tottenham,0,0.000000,4.801015,4.801015
311,311,745,Kasper Schmeichel,38,3420,0,0.000000,0,0.000000,0,0,0,0,GK,Leicester,0,0.000000,3.868818,3.868818
378,378,4401,Emiliano Martinez,38,3420,0,0.000000,0,0.122923,0,2,1,0,GK,Aston Villa,0,0.000000,3.730909,3.607986
40,40,8718,Stuart Dallas,38,3412,8,4.457074,2,2.084683,48,26,7,0,D M,Leeds,8,4.457074,18.534344,13.809802
327,327,884,Matt Targett,38,3407,0,0.280304,2,2.799669,6,39,7,0,D,Aston Villa,0,0.280304,9.610859,8.203313
480,480,8716,Luke Ayling,38,3400,0,1.439750,0,2.988854,24,26,7,0,D M,Leeds,0,1.439750,14.196262,11.884364
204,204,1688,Andrew Robertson,38,3391,1,1.437934,7,7.220492,19,65,2,0,D,Liverpool,1,1.437934,19.869482,15.435009
55,55,5956,Youri Tielemans,38,3359,6,4.168204,4,3.312251,48,49,6,0,M S,Leicester,4,2.645866,18.975342,14.945469
7,7,8865,Ollie Watkins,37,3330,14,16.280178,5,5.314029,98,45,2,1,F,Aston Villa,13,14.757840,22.014021,5.334991

**10 Player terbanyak assist**

In [9]:
assist = data['assists'].value_counts()
assist

0     277
1      97
2      55
3      32
5      21
4      13
6       8
7       7
8       4
9       3
10      2
14      1
12      1
11      1
Name: assists, dtype: int64

In [10]:
assist = data.nlargest(10,'assists')
assist

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
58,58,447,Kevin De Bruyne,24,1918,5,9.908440,11,10.003763,79,72,1,0,M S,Manchester City,3,7.624933,21.079132,10.636448
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
51,51,675,Jack Grealish,26,2187,6,5.192684,10,9.334137,50,81,5,0,F M S,Aston Villa,6,5.192684,17.487469,6.972044
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,28,1,0,F S,Leicester,7,13.092427,18.227907,2.412588
15,15,556,Marcus Rashford,37,2941,11,9.579710,9,4.185122,79,44,4,0,F M S,Manchester United,11,9.579710,20.441910,8.927208
57,57,8026,Raphinha,30,2369,6,6.219143,9,9.524861,67,65,3,0,M S,Leeds,6,6.219143,16.792778,6.679692
41,41,8720,Jack Harrison,36,2871,8,6.254043,8,7.523059,46,59,2,0,M S,Leeds,8,6.254043,19.397490,8.035575
49,49,65,Timo Werner,35,2605,6,13.432796,8,6.667277,80,36,2,0,F M S,Chelsea,6,13.432796,20.533463,5.242122

**4 Player pencetak goal terbanyak dari MNC**

In [11]:
club_syarat = 'Manchester City'
pemainmnc = data[data['team_title'] == club_syarat]

mostgoalmnc = pemainmnc.sort_values(by='goals', ascending=False).head(10)
mostgoalmnc

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
8,8,314,Ilkay GÃ¼ndogan,28,2033,13,9.566883,2,3.816220,54,42,1,0,M S,Manchester City,12,8.044545,19.286812,10.148375
22,22,618,Raheem Sterling,30,2449,10,11.763264,6,5.817096,68,35,3,0,F M S,Manchester City,10,11.002095,24.088666,11.477125
28,28,750,Riyad Mahrez,26,1894,9,6.151046,5,5.954979,56,43,0,0,F M S,Manchester City,9,6.151046,18.641168,9.019600
35,35,5543,Gabriel Jesus,28,1977,8,9.009614,4,3.371890,52,29,2,0,F M S,Manchester City,8,9.009614,16.564744,5.563635
37,37,6055,Phil Foden,27,1548,8,5.437581,5,4.749281,43,36,0,0,F M S,Manchester City,8,5.437581,13.111077,5.408362
46,46,6441,FerrÃ¡n Torres,23,1291,7,5.728708,2,2.202426,36,18,1,0,F M S,Manchester City,7,5.728708,9.768891,2.724257
58,58,447,Kevin De Bruyne,24,1918,5,9.908440,11,10.003763,79,72,1,0,M S,Manchester City,3,7.624933,21.079132,10.636448
70,70,586,John Stones,21,1843,4,2.393954,0,0.046840,14,2,0,1,D,Manchester City,4,2.393954,9.842464,9.742795
132,132,2496,Rodri,33,2719,2,2.538604,2,2.335383,31,33,6,0,M S,Manchester City,1,1.777435,20.214505,18.323006
135,135,3389,Benjamin Mendy,13,955,2,0.334141,1,0.301440,6,5,2,0,D M S,Manchester City,2,0.334141,2.769137,2.348603

**Dari kesebelasan mana pencetak goal terbanyak**

In [18]:
club = data.groupby('team_title')['goals'].sum().reset_index()
terbaikbasedgoal = club.loc[club['goals'].idxmax()]
print(f"\nClub dengan goal terbanyak:")
print(terbaikbasedgoal)

Club dengan goal terbanyak:
team_title    Manchester City
goals                      77
Name: 18, dtype: object

**Berapa jumlah kartu kuning dan merah yang diterima pembuat asssist terbanyak**

In [23]:
most_assist = data['assists'].max()
pemain_assist = data[data['assists'] == most_assist]
show_pemain = pemain_assist[['player_name', 'assists', 'yellow_cards','red_cards']]
show_pemain

  player_name  assists  yellow_cards  red_cards
0  Harry Kane       14             1          0

**Siapa yang jumlah assist dan goalnya paling banyak dan dari kesebelasan mana?**

In [29]:
most_assist_2 = data['assists'].max()
pemain_assist_2 = data[data['assists'] == most_assist_2]
show_pemain = pemain_assist_2[['player_name', 'assists', 'team_title']]
show_pemain

  player_name  assists team_title
0  Harry Kane       14  Tottenham

In [30]:
most_goal_2 = data['goals'].max()
pemain_goal_2 = data[data['goals'] == most_goal_2]
show_pemain_goal = pemain_goal_2[['player_name', 'goals', 'team_title']]
show_pemain_goal

  player_name  goals team_title
0  Harry Kane     23  Tottenham

In [38]:
most_most_again = data[(data['goals'] == most_goal_2) & (data['assists'] == most_assist_2)]
most_most_player = most_most_again[['player_name', 'assists', 'team_title']]
most_most_player

  player_name  assists team_title
0  Harry Kane       14  Tottenham

**5 Kesebelasan yang menyumbang goal terbanyak**

In [35]:
club_5 = data.groupby('team_title')['goals'].sum().reset_index()
terbaikbasedgoal_5 = club_5.sort_values(by='goals', ascending=False)
again = terbaikbasedgoal_5.head(5)
again

           team_title  goals
18    Manchester City     77
19  Manchester United     68
23          Tottenham     66
16          Liverpool     64
15          Leicester     64

**Urutkan pemain berdasarkan jumlah goal terbanyak tanpa mendapatkan kartu sama sekali**

In [45]:
without_card = data[(data['yellow_cards'] == 0) & (data['red_cards'] == 0)]
most_goal_3 = without_card['goals'].max()
top_10 = without_card.head(10)
top_10

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
13,13,4456,Chris Wood,32,2675,12,12.896009,3,2.038118,69,23,0,0,F S,Burnley,10,11.373671,13.585282,2.149852
28,28,750,Riyad Mahrez,26,1894,9,6.151046,5,5.954979,56,43,0,0,F M S,Manchester City,9,6.151046,18.641168,9.019600
29,29,6681,Harvey Barnes,25,1954,9,6.697320,4,1.771688,56,26,0,0,F M S,Leicester,9,6.697320,8.893774,1.594841
33,33,1776,Jarrod Bowen,37,2514,8,7.817086,5,4.952178,53,28,0,0,F M S,West Ham,8,7.817086,14.000131,3.096995
37,37,6055,Phil Foden,27,1548,8,5.437581,5,4.749281,43,36,0,0,F M S,Manchester City,8,5.437581,13.111077,5.408362
50,50,501,Danny Welbeck,24,1551,6,7.380382,1,3.231367,35,22,0,0,F M S,Brighton,6,6.619249,10.265667,1.476513
52,52,702,Tammy Abraham,22,1027,6,6.189151,1,0.721487,32,9,0,0,F S,Chelsea,6,6.189151,7.901170,2.122328
60,60,4476,Callum Robinson,28,1580,5,3.203063,0,1.049963,31,16,0,0,F M S,West Bromwich Albion,5,3.203063,5.216541,1.596336